# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PjvCCz8BZhI6Md0tFek5hPg-XXhLUJD9
"""

# ==========================================
# INSTALL
# ==========================================

!pip install -q gradio groq gtts

# ==========================================
# IMPORTS
# ==========================================

import gradio as gr
from groq import Groq
from gtts import gTTS
import uuid

# ==========================================
# GROQ API KEY
# ==========================================

GROQ_API_KEY = "YOUR GROQ API KEY"

client = Groq(api_key=GROQ_API_KEY)

# ==========================================
# AI FUNCTION
# ==========================================

def analyze_crop(crop, symptoms, language):

    if crop.strip() == "":
        return "Please enter crop name.", None

    if symptoms.strip() == "":
        return "Please enter symptoms.", None

    prompt = f"""
You are AI Crop Doctor.

Reply ONLY in {language}.

Give output in this format:

🌱 Crop Health Summary

🔍 Possible Causes

🐛 Possible Disease or Pest

💧 Irrigation Advice

🌿 Fertilizer Suggestions

🛡 Prevention Tips

📈 Yield Improvement Suggestions

✅ Final Recommendation

Crop:
{crop}

Symptoms:
{symptoms}
"""

    try:

        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )

        result = response.choices[0].message.content

    except Exception as e:

        result = f"Error:\n{str(e)}"

    audio_file = None

    try:

        lang_map = {
            "English": "en",
            "Telugu": "te",
            "Hindi": "hi"
        }

        audio_file = f"{uuid.uuid4()}.mp3"

        gTTS(
            text=result[:2500],
            lang=lang_map[language]
        ).save(audio_file)

    except:
        pass

    return result, audio_file

# ==========================================
# CUSTOM CSS
# ==========================================

css = """
body{
background:#f3f8f3;
}

.gradio-container{
max-width:1100px !important;
margin:auto !important;
}

.hero{
padding:25px;
border-radius:20px;
background:linear-gradient(90deg,#1b5e20,#43a047);
color:white;
text-align:center;
margin-bottom:20px;
}

.footer{
text-align:center;
padding:10px;
font-size:14px;
}
"""

# ==========================================
# UI
# ==========================================

with gr.Blocks(css=css, theme=gr.themes.Soft()) as demo:

    gr.HTML("""
    <div class="hero">
        <h1>🌾 AI Crop Doctor</h1>
        <h3>Smart Agriculture Assistant Powered by Groq</h3>
        <p>
        Crop Health • Fertilizer Advice • Irrigation Planning • Pest Guidance
        </p>
    </div>
    """)

    with gr.Row():

        crop = gr.Textbox(
            label="🌱 Crop Name",
            placeholder="Rice, Cotton, Tomato, Chilli..."
        )

        language = gr.Dropdown(
            ["English","Telugu","Hindi"],
            value="English",
            label="🌍 Output Language"
        )

    symptoms = gr.Textbox(
        lines=6,
        label="📝 Symptoms / Question",
        placeholder="Leaves turning yellow, brown spots, poor growth..."
    )

    analyze_btn = gr.Button(
        "🚀 Analyze Crop"
    )

    output = gr.Textbox(
        lines=20,
        label="🤖 AI Response"
    )

    audio = gr.Audio(
        label="🔊 Voice Output"
    )

    analyze_btn.click(
        analyze_crop,
        inputs=[
            crop,
            symptoms,
            language
        ],
        outputs=[
            output,
            audio
        ]
    )

    gr.HTML("""
    <div class="footer">
    🌾 AI Crop Doctor | Powered by Groq
    </div>
    """)

# ==========================================
# LAUNCH
# ==========================================

demo.launch(
    share=True,
    debug=True
)